spring.application.name=banquito-switch-sftp-service
server.port=${SERVER_PORT:8090}

management.endpoints.web.exposure.include=health,info

sftp.enabled=${SFTP_ENABLED:true}
sftp.port=${SFTP_PORT:2222}
sftp.base-directory=${SFTP_BASE_DIRECTORY:/app/sftp}
sftp.upload-directory=${SFTP_UPLOAD_DIRECTORY:/app/sftp/upload}
sftp.processed-directory=${SFTP_PROCESSED_DIRECTORY:/app/sftp/processed}
sftp.rejected-directory=${SFTP_REJECTED_DIRECTORY:/app/sftp/rejected}
sftp.scan-delay-ms=${SFTP_SCAN_DELAY_MS:2000}
sftp.file-stable-ms=${SFTP_FILE_STABLE_MS:1500}

sftp.demo-user.username=${SFTP_USER_EMPRESA_SIERRAAZUL_USERNAME:empresa.sierraazul}
sftp.demo-user.password=${SFTP_USER_EMPRESA_SIERRAAZUL_PASSWORD:Password123!}
sftp.demo-user.company-ruc=${SFTP_USER_EMPRESA_SIERRAAZUL_COMPANY_RUC:1792103456001}

batch-service.base-url=${BATCH_SERVICE_BASE_URL:http://batch-service:8081}
batch-service.upload-path=${BATCH_SERVICE_UPLOAD_PATH:/api/v1/batches/upload}
batch-service.connect-timeout-ms=${BATCH_SERVICE_CONNECT_TIMEOUT_MS:5000}
batch-service.read-timeout-ms=${BATCH_SERVICE_READ_TIMEOUT_MS:60000}
